import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import PersonalInfoTab from "./components/PersonalInfoTab";
import EmergencyContactTab from "./components/EmergencyContactTab";
import DocumentRequestTab from "./components/DocumentRequestTab";
import FileUploadTab from "./components/FileUploadTab";
import MyRequestsTab from "./components/MyRequestsTab";
import { CheckCircle, AlertCircle, Loader2, FileText, Clock, Bell, ArrowRight, X, Sparkles } from "lucide-react";
import { useAuth } from "../../../context/AuthContext";
import axios from "axios";
import { motion, AnimatePresence } from "framer-motion";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";

const tabs = [
  { id: "request", label: "1. Select Document", step: 1 },
  { id: "personal", label: "2. Review Info", step: 2 },
  { id: "files", label: "3. Upload ID", step: 3 },
  { id: "my-requests", label: "My Requests", step: 0 },
];

const initialForm = {
  // Personal (will be auto-filled from user)
  lastName: "",
  firstName: "",
  middleName: "",
  suffix: "",
  dateOfBirth: "",
  placeOfBirth: "",
  gender: "",
  civilStatus: "",
  salutation: "",
  nationality: "",
  // Address (atomic structure)
  subdivision: "",
  street: "",
  houseNumber: "",
  contactNumber: "",
  // Additional fields from form
  tinNumber: "",
  sssGsisNumber: "",
  precinctNumber: "",
  religion: "",
  heightWeight: "",
  colorOfHairEyes: "",
  occupation: "",
  emailAddress: "",
  // Spouse info
  spouseName: "",
  spouseOccupation: "",
  spouseContact: "",
  // Emergency Contact
  emergencyName: "",
  emergencyRelationship: "",
  emergencyContact: "",
  emergencySubdivision: "",
  emergencyStreet: "",
  emergencyHouseNumber: "",
  // File uploads
  photo1x1File: null,
  validIDFile: null,
  // Business Info (for business documents)
  businessName: "",
  businessSubdivision: "",
  businessStreet: "",
  businessHouseNumber: "",
  applicationType: "",
  natureOfBusiness: "",
  ownerRepresentative: "",
  ownerContactNumber: "",
  representativeContactNumber: "",
  // Business Permit specific
  fees: "",
  orNumber: "",
  // Business Closure specific
  closureDate: "",
  // Request
  documentType: "",
  requestFor: "",
  purposeOfRequest: "",
  remarks: "",
  // Beneficiary Info (for rehab certificates)
  beneficiaryFullName: "",
  beneficiaryDateOfBirth: "",
  beneficiaryAge: "",
  beneficiaryRelationship: "",
  // Residency specific - only residencySince is user-provided
  // referenceNo, documentFileNo, preparedBy are auto-generated by backend
  residencySince: "",
  // Barangay ID specific
  residencyType: "",
  // Missionary specific (foreign national)
  acrNumber: "",
  acrValidUntil: "",
  passportNumber: "",
};

export default function Services() {
  const navigate = useNavigate();
  const [active, setActive] = useState("request");
  const [formData, setFormData] = useState(initialForm);
  const [errors, setErrors] = useState({});
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [showError, setShowError] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [loading, setLoading] = useState(false);
  const [autoFilling, setAutoFilling] = useState(true);
  const [showLoadingToast, setShowLoadingToast] = useState(true); // Start with loading visible
  const [hasLoadedData, setHasLoadedData] = useState(false);
  const { user, loading: authLoading } = useAuth();

  // Load form data from localStorage on mount
  useEffect(() => {
    const savedFormData = localStorage.getItem("documentRequestForm");

    if (savedFormData) {
      try {
        const parsedData = JSON.parse(savedFormData);

        // Check if saved data has meaningful content (not just empty strings)
        const hasContent =
          parsedData.firstName || parsedData.lastName || parsedData.email;

        if (hasContent) {
          // Don't restore file objects, only text data
          const { photo1x1File, validIDFile, ...restData } = parsedData;
          setFormData((prev) => ({
            ...prev,
            ...restData,
          }));
          setAutoFilling(false); // Skip auto-fill if we have saved data
          setHasLoadedData(true);
          setShowLoadingToast(false); // Hide loading immediately
        } else {
          localStorage.removeItem("documentRequestForm"); // Clear empty data
          setShowLoadingToast(true);
        }
      } catch (error) {
        setShowLoadingToast(true); // Keep showing loading on error
      }
    } else {
      // Keep loading visible until user data arrives
      setShowLoadingToast(true);
    }
  }, []);

  // Auto-fill form from user data (only if no saved data and haven't auto-filled yet)
  useEffect(() => {
    // If we already have loaded data, hide loading and exit
    if (hasLoadedData) {
      setShowLoadingToast(false);
      return;
    }

    // Wait for auth to finish loading
    if (authLoading) {
      setShowLoadingToast(true);
      return;
    }

    // If auth finished but no user, something went wrong - hide loading
    if (!authLoading && !user) {
      setShowLoadingToast(false);
      return;
    }

    if (user && autoFilling) {
      setShowLoadingToast(true);

      // Format date of birth to YYYY-MM-DD for HTML date input
      const formatDate = (dateString) => {
        if (!dateString) return "";
        try {
          const date = new Date(dateString);
          if (isNaN(date.getTime())) return "";
          return date.toISOString().split("T")[0];
        } catch (error) {
          return "";
        }
      };

      const formattedDate = formatDate(user.dateOfBirth);

      const newFormData = {
        ...formData,
        lastName: user.lastName || "",
        firstName: user.firstName || "",
        middleName: user.middleName || "",
        suffix: user.suffix || "",
        dateOfBirth: formattedDate,
        placeOfBirth: user.placeOfBirth || "",
        gender: user.gender || "",
        civilStatus: user.civilStatus || "",
        salutation: user.salutation || "",
        nationality: user.nationality || "Filipino",
        contactNumber: user.phoneNumber || "",
        emailAddress: user.email || "",
        // Address
        subdivision: user.address?.subdivision || "",
        street: user.address?.street || "",
        houseNumber: user.address?.houseNumber || "",
        // Additional fields from user registration
        tinNumber: user.tinNumber || "",
        sssGsisNumber: user.sssGsisNumber || "",
        precinctNumber: user.precinctNumber || "",
        religion: user.religion || "",
        heightWeight: user.heightWeight || "",
        colorOfHairEyes: user.colorOfHairEyes || "",
        occupation: user.occupation || "",
        // Spouse info
        spouseName: user.spouseInfo?.name || "",
        spouseOccupation: user.spouseInfo?.occupation || "",
        spouseContact: user.spouseInfo?.contactNumber || "",
        // Emergency contact
        emergencyName: user.emergencyContact?.fullName || "",
        emergencyRelationship: user.emergencyContact?.relationship || "",
        emergencyContact: user.emergencyContact?.contactNumber || "",
        emergencySubdivision: user.emergencyContact?.address?.subdivision || "",
        emergencyStreet: user.emergencyContact?.address?.street || "",
        emergencyHouseNumber: user.emergencyContact?.address?.houseNumber || "",
      };

      setFormData(newFormData);
      setAutoFilling(false);
      setHasLoadedData(true);

      // Hide loading toast after a short delay to show completion
      setTimeout(() => {
        setShowLoadingToast(false);
      }, 800);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user, autoFilling, hasLoadedData, authLoading]);

  // Save form data to localStorage whenever it changes
  useEffect(() => {
    if (!autoFilling && formData !== initialForm) {
      // Save to localStorage (excluding file objects)
      const { photo1x1File, validIDFile, ...dataToSave } = formData;
      localStorage.setItem("documentRequestForm", JSON.stringify(dataToSave));
    }
  }, [formData, autoFilling]);

  const setField = (name, value) =>
    setFormData((p) => ({ ...p, [name]: value }));

  const isBusinessDocument = () => {
    return ["business_permit", "business_clearance", "liquor_permit"].includes(
      formData.documentType
    );
  };

  const validateAll = () => {
    const e = {};
    // Required personal fields
    if (!formData.lastName.trim()) e.lastName = "Last Name is required";
    if (!formData.firstName.trim()) e.firstName = "First name is required";
    if (!formData.dateOfBirth) e.dateOfBirth = "Date of birth is required";
    if (!formData.gender) e.gender = "Gender is required";
    if (!formData.contactNumber.trim())
      e.contactNumber = "Contact number is required";

    // File uploads
    if (!formData.validIDFile) e.validIDFile = "Valid ID is required";

    // Emergency contact
    if (!formData.emergencyName.trim())
      e.emergencyName = "Emergency contact name is required";
    if (!formData.emergencyContact.trim())
      e.emergencyContact = "Emergency contact number is required";

    // Document request
    if (!formData.documentType) e.documentType = "Select a document type";
    if (!formData.purposeOfRequest.trim())
      e.purposeOfRequest = "Purpose is required";

    // Photo 1x1 required only for residency
    if (formData.documentType === "residency" && !formData.photo1x1File) {
      e.photo1x1File = "Photo 1x1 is required for Certificate of Residency";
    }

    // Business fields validation
    if (isBusinessDocument()) {
      if (!formData.businessName.trim())
        e.businessName = "Business name is required";
      // Only require natureOfBusiness for business_permit (not business_clearance or liquor_permit)
      if (
        formData.documentType === "business_permit" &&
        !formData.natureOfBusiness.trim()
      ) {
        e.natureOfBusiness = "Nature of business is required";
      }
      // Require closureDate for business_clearance
      if (
        formData.documentType === "business_clearance" &&
        !formData.closureDate
      ) {
        e.closureDate = "Closure date is required";
      }
    }

    // Beneficiary fields validation for rehab certificates
    if (formData.documentType === "rehab") {
      if (!formData.beneficiaryFullName?.trim())
        e.beneficiaryFullName = "Beneficiary name is required";
      if (!formData.beneficiaryDateOfBirth)
        e.beneficiaryDateOfBirth = "Beneficiary date of birth is required";
      if (!formData.beneficiaryAge)
        e.beneficiaryAge = "Beneficiary age is required";
      if (!formData.beneficiaryRelationship)
        e.beneficiaryRelationship = "Relationship is required";
    }

    // Residency certificate validation
    if (formData.documentType === "residency") {
      if (!formData.residencySince?.trim())
        e.residencySince = "Residing in Barangay Since is required";
    }

    // Barangay ID validation
    if (formData.documentType === "barangay_id") {
      if (!formData.residencyType)
        e.residencyType = "Residency type is required for Barangay ID";
    }

    // Missionary certificate validation - all fields required with format validation
    if (formData.documentType === "missionary") {
      // Nationality is required (already checked in general validation above)

      // ACR Number - required and must match format
      if (!formData.acrNumber?.trim()) {
        e.acrNumber = "ACR Number is required";
      } else {
        const acrPattern = /^[A-Z]\d{10}$/;
        if (!acrPattern.test(formData.acrNumber.trim())) {
          e.acrNumber =
            "ACR Number must be 1 uppercase letter followed by 10 digits (e.g., G0000156451)";
        }
      }

      // ACR Valid Until - required and must be future date
      if (!formData.acrValidUntil) {
        e.acrValidUntil = "ACR expiration date is required";
      } else {
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        const validUntil = new Date(formData.acrValidUntil);
        if (validUntil < today) {
          e.acrValidUntil = "ACR expiration date must be in the future";
        }
      }

      // Passport Number - required and must match format
      if (!formData.passportNumber?.trim()) {
        e.passportNumber = "Passport Number is required";
      } else {
        const passportPattern = /^[A-Z0-9]{6,9}$/i;
        if (!passportPattern.test(formData.passportNumber.trim())) {
          e.passportNumber =
            "Passport Number must be 6-9 alphanumeric characters (e.g., C4366706)";
        }
      }
    }

    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (loading) return; // Prevent duplicate submissions
    if (!validateAll()) {
      // Navigate to first error tab
      if (
        Object.keys(errors).some((k) =>
          ["lastName", "firstName", "dateOfBirth", "gender"].includes(k)
        )
      ) {
        setActive("personal");
      } else if (
        Object.keys(errors).some((k) =>
          ["emergencyName", "emergencyContact"].includes(k)
        )
      ) {
        setActive("emergency");
      } else if (
        Object.keys(errors).some((k) =>
          ["photo1x1File", "validIDFile"].includes(k)
        )
      ) {
        setActive("files");
      } else {
        setActive("request");
      }
      return;
    }

    setLoading(true);
    setShowError(false);

    try {
      // Create FormData for file upload
      const formDataToSend = new FormData();

      // Personal info
      formDataToSend.append("lastName", formData.lastName);
      formDataToSend.append("firstName", formData.firstName);
      if (formData.middleName)
        formDataToSend.append("middleName", formData.middleName);
      if (formData.dateOfBirth)
        formDataToSend.append("dateOfBirth", formData.dateOfBirth);
      if (formData.placeOfBirth)
        formDataToSend.append("placeOfBirth", formData.placeOfBirth);
      if (formData.gender) formDataToSend.append("gender", formData.gender);
      if (formData.civilStatus)
        formDataToSend.append("civilStatus", formData.civilStatus);
      if (formData.salutation)
        formDataToSend.append("salutation", formData.salutation);
      if (formData.nationality)
        formDataToSend.append("nationality", formData.nationality);
      if (formData.contactNumber)
        formDataToSend.append("contactNumber", formData.contactNumber);

      // Address
      formDataToSend.append("address[subdivision]", formData.subdivision || "");
      formDataToSend.append("address[street]", formData.street || "");
      formDataToSend.append("address[houseNumber]", formData.houseNumber || "");

      // Additional fields
      if (formData.tinNumber)
        formDataToSend.append("tinNumber", formData.tinNumber);
      if (formData.sssGsisNumber)
        formDataToSend.append("sssGsisNumber", formData.sssGsisNumber);
      if (formData.precinctNumber)
        formDataToSend.append("precinctNumber", formData.precinctNumber);
      if (formData.religion)
        formDataToSend.append("religion", formData.religion);
      if (formData.heightWeight)
        formDataToSend.append("heightWeight", formData.heightWeight);
      if (formData.colorOfHairEyes)
        formDataToSend.append("colorOfHairEyes", formData.colorOfHairEyes);
      if (formData.occupation)
        formDataToSend.append("occupation", formData.occupation);
      if (formData.emailAddress)
        formDataToSend.append("emailAddress", formData.emailAddress);

      // Spouse info
      if (formData.spouseName)
        formDataToSend.append("spouseInfo[name]", formData.spouseName);
      if (formData.spouseOccupation)
        formDataToSend.append(
          "spouseInfo[occupation]",
          formData.spouseOccupation
        );
      if (formData.spouseContact)
        formDataToSend.append(
          "spouseInfo[contactNumber]",
          formData.spouseContact
        );

      // Emergency contact
      formDataToSend.append(
        "emergencyContact[fullName]",
        formData.emergencyName
      );
      if (formData.emergencyRelationship)
        formDataToSend.append(
          "emergencyContact[relationship]",
          formData.emergencyRelationship
        );
      formDataToSend.append(
        "emergencyContact[contactNumber]",
        formData.emergencyContact
      );
      formDataToSend.append(
        "emergencyContact[address][subdivision]",
        formData.emergencySubdivision || ""
      );
      formDataToSend.append(
        "emergencyContact[address][street]",
        formData.emergencyStreet || ""
      );
      formDataToSend.append(
        "emergencyContact[address][houseNumber]",
        formData.emergencyHouseNumber || ""
      );

      // Business info (if applicable)
      if (isBusinessDocument()) {
        formDataToSend.append(
          "businessInfo[businessName]",
          formData.businessName
        );
        formDataToSend.append(
          "businessInfo[natureOfBusiness]",
          formData.natureOfBusiness
        );
        if (formData.applicationType)
          formDataToSend.append(
            "businessInfo[applicationType]",
            formData.applicationType
          );
        if (formData.ownerRepresentative)
          formDataToSend.append(
            "businessInfo[ownerRepresentative]",
            formData.ownerRepresentative
          );
        if (formData.ownerContactNumber)
          formDataToSend.append(
            "businessInfo[ownerContactNumber]",
            formData.ownerContactNumber
          );
        if (formData.representativeContactNumber)
          formDataToSend.append(
            "businessInfo[representativeContactNumber]",
            formData.representativeContactNumber
          );
        formDataToSend.append(
          "businessInfo[businessAddress][subdivision]",
          formData.businessSubdivision || ""
        );
        formDataToSend.append(
          "businessInfo[businessAddress][street]",
          formData.businessStreet || ""
        );
        formDataToSend.append(
          "businessInfo[businessAddress][houseNumber]",
          formData.businessHouseNumber || ""
        );
      }

      formDataToSend.append("documentType", formData.documentType);
      formDataToSend.append("purposeOfRequest", formData.purposeOfRequest);
      // Use purposeOfRequest for requestFor as well (merged fields)
      formDataToSend.append("requestFor", formData.purposeOfRequest);
      if (formData.remarks) formDataToSend.append("remarks", formData.remarks);

      // Beneficiary info (for rehab certificates)
      if (formData.documentType === "rehab") {
        formDataToSend.append(
          "beneficiaryInfo[fullName]",
          formData.beneficiaryFullName
        );
        formDataToSend.append(
          "beneficiaryInfo[dateOfBirth]",
          formData.beneficiaryDateOfBirth
        );
        formDataToSend.append("beneficiaryInfo[age]", formData.beneficiaryAge);
        formDataToSend.append(
          "beneficiaryInfo[relationship]",
          formData.beneficiaryRelationship
        );
      }

      // Residency specific fields - only residencySince is user-provided
      // referenceNo, documentFileNo, and preparedBy are auto-generated by backend
      if (formData.documentType === "residency") {
        if (formData.residencySince)
          formDataToSend.append(
            "residencyInfo[residencySince]",
            formData.residencySince
          );
      }

      // Barangay ID specific fields
      if (formData.documentType === "barangay_id") {
        if (formData.residencyType)
          formDataToSend.append("residencyType", formData.residencyType);
        // Note: civilStatus and precinctNumber are already appended in the main personal info section
      }

      // Missionary specific fields (foreign national info)
      if (formData.documentType === "missionary") {
        if (formData.acrNumber)
          formDataToSend.append(
            "foreignNationalInfo[acrNumber]",
            formData.acrNumber
          );
        if (formData.acrValidUntil)
          formDataToSend.append(
            "foreignNationalInfo[acrValidUntil]",
            formData.acrValidUntil
          );
        if (formData.passportNumber)
          formDataToSend.append(
            "foreignNationalInfo[passportNumber]",
            formData.passportNumber
          );
      }

      // Business Permit specific fields
      if (formData.documentType === "business_permit") {
        if (formData.fees) formDataToSend.append("fees", formData.fees);
        if (formData.orNumber)
          formDataToSend.append("businessInfo[orNumber]", formData.orNumber);
      }

      // Business Closure specific fields
      if (formData.documentType === "business_clearance") {
        if (formData.closureDate)
          formDataToSend.append(
            "businessInfo[closureDate]",
            formData.closureDate
          );
      }

      // Files - only append new files, not stored ones (stored files are identified by isStored flag)
      // When using stored files, the backend will reuse the files from user profile
      if (formData.photo1x1File && !formData.photo1x1File.isStored) {
        formDataToSend.append("photo1x1", formData.photo1x1File);
      } else if (formData.photo1x1File?.isStored) {
        // Tell backend to use stored photo from user profile
        formDataToSend.append("useStoredPhoto1x1", "true");
      }

      if (formData.validIDFile && !formData.validIDFile.isStored) {
        formDataToSend.append("validID", formData.validIDFile);
      } else if (formData.validIDFile?.isStored) {
        // Tell backend to use stored valid ID from user profile
        formDataToSend.append("useStoredValidID", "true");
      }

      const token = localStorage.getItem("token");
      const response = await axios.post(
        `${API_URL}/api/document-requests`,
        formDataToSend,
        {
          headers: {
            "Content-Type": "multipart/form-data",
            Authorization: `Bearer ${token}`,
          },
        }
      );

      // Show success modal
      setShowSuccessModal(true);
      setShowError(false);

      // Reset form
      setFormData(initialForm);
      setAutoFilling(true); // Re-enable auto-fill for next request
      setHasLoadedData(false); // Allow auto-fill on next visit
      localStorage.removeItem("documentRequestForm"); // Clear saved form data

      // Scroll to top
      window.scrollTo({ top: 0, behavior: "smooth" });
    } catch (error) {
      console.error("Submit error:", error);
      setErrorMessage(
        error.response?.data?.message ||
          error.response?.data?.error ||
          "Failed to submit request. Please try again."
      );
      setShowError(true);
      setTimeout(() => setShowError(false), 5000);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      className="min-h-screen"
      style={{ backgroundColor: "var(--color-neutral)" }}
    >
      {/* Hero Section with Animation */}
      <motion.section
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6 }}
        className="relative text-white overflow-hidden"
        style={{
          background:
            "linear-gradient(135deg, var(--color-secondary) 0%, var(--color-secondary-glow) 100%)",
        }}
      >
        {/* Decorative Background Pattern */}
        <div className="absolute inset-0 opacity-10">
          <div
            className="absolute inset-0"
            style={{
              backgroundImage: `radial-gradient(circle at 2px 2px, white 1px, transparent 0)`,
              backgroundSize: "40px 40px",
            }}
          ></div>
        </div>

        <div className="relative max-w-6xl mx-auto px-4 sm:px-6 pt-24 pb-12 sm:pt-28 sm:pb-16 md:pt-36 md:pb-28 text-center">
          {/* Animated Icon Badge */}
          <motion.div
            initial={{ scale: 0, rotate: -180 }}
            animate={{ scale: 1, rotate: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="inline-flex items-center justify-center w-12 h-12 sm:w-16 sm:h-16 md:w-20 md:h-20 bg-white/20 backdrop-blur-sm rounded-full mb-4 sm:mb-6"
          >
            <FileText className="w-6 h-6 sm:w-8 sm:h-8 md:w-10 md:h-10" />
          </motion.div>

          {/* Title */}
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="text-2xl sm:text-4xl md:text-6xl lg:text-7xl font-extrabold mb-3 sm:mb-4 md:mb-6 max-w-3xl mx-auto"
          >
            Barangay Services
          </motion.h1>

          {/* Description */}
          <motion.p
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.5 }}
            className="text-sm sm:text-lg md:text-xl text-white/90 max-w-2xl leading-relaxed mx-auto px-2"
          >
            Request your official barangay documents online quickly and
            securely. Fill out the form below and track your request status.
          </motion.p>
        </div>

        {/* Wave Divider */}
        <div
          className="absolute bottom-0 left-0 w-full overflow-hidden leading-none"
          style={{ transform: "rotate(180deg)" }}
        >
          <svg
            className="relative block w-full h-8 sm:h-12 md:h-20"
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 1200 120"
            preserveAspectRatio="none"
          >
            <path
              d="M321.39,56.44c58-10.79,114.16-30.13,172-41.86,82.39-16.72,168.19-17.73,250.45-.39C823.78,31,906.67,72,985.66,92.83c70.05,18.48,146.53,26.09,214.34,3V0H0V27.35A600.21,600.21,0,0,0,321.39,56.44Z"
              fill="var(--color-neutral)"
            ></path>
          </svg>
        </div>
      </motion.section>

      {/* Success Modal */}
      <AnimatePresence>
        {showSuccessModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[9999] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm"
            onClick={() => setShowSuccessModal(false)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              transition={{ type: "spring", damping: 25, stiffness: 300 }}
              onClick={(e) => e.stopPropagation()}
              className="relative w-full max-w-md bg-white dark:bg-gray-800 rounded-2xl shadow-2xl overflow-hidden"
            >
              {/* Success Header with Gradient */}
              <div className="relative bg-gradient-to-r from-green-600 via-emerald-600 to-teal-600 px-6 py-8 overflow-hidden">
                {/* Background pattern */}
                <div className="absolute inset-0 opacity-10">
                  <div
                    className="absolute inset-0"
                    style={{
                      backgroundImage: `radial-gradient(circle at 2px 2px, white 1px, transparent 0)`,
                      backgroundSize: "20px 20px",
                    }}
                  />
                </div>

                {/* Sparkle effects */}
                <motion.div
                  animate={{
                    scale: [1, 1.2, 1],
                    opacity: [0.5, 1, 0.5],
                  }}
                  transition={{
                    duration: 2,
                    repeat: Infinity,
                    repeatType: "reverse",
                  }}
                  className="absolute top-4 right-16"
                >
                  <Sparkles className="w-5 h-5 text-white/60" />
                </motion.div>
                <motion.div
                  animate={{
                    scale: [1, 1.3, 1],
                    opacity: [0.3, 0.8, 0.3],
                  }}
                  transition={{
                    duration: 2.5,
                    repeat: Infinity,
                    repeatType: "reverse",
                    delay: 0.5,
                  }}
                  className="absolute bottom-6 left-12"
                >
                  <Sparkles className="w-4 h-4 text-white/40" />
                </motion.div>

                {/* Close button */}
                <button
                  onClick={() => setShowSuccessModal(false)}
                  className="absolute top-4 right-4 p-1.5 rounded-lg hover:bg-white/10 transition-colors"
                >
                  <X className="w-5 h-5 text-white" />
                </button>

                {/* Success Icon */}
                <div className="relative z-10 flex flex-col items-center text-center">
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: "spring", delay: 0.2, stiffness: 200 }}
                    className="w-20 h-20 rounded-full bg-white/20 backdrop-blur flex items-center justify-center mb-4"
                  >
                    <motion.div
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      transition={{ type: "spring", delay: 0.4, stiffness: 200 }}
                    >
                      <CheckCircle className="w-10 h-10 text-white" />
                    </motion.div>
                  </motion.div>
                  <h3 className="text-2xl font-bold text-white mb-2">
                    Request Submitted! 🎉
                  </h3>
                  <p className="text-green-100 text-sm">
                    Your document request has been sent successfully
                  </p>
                </div>
              </div>

              {/* Content */}
              <div className="p-6 space-y-4">
                {/* Processing time info */}
                <div className="flex items-start gap-3 p-4 bg-blue-50 dark:bg-blue-900/20 rounded-xl border border-blue-200 dark:border-blue-800">
                  <div className="w-10 h-10 rounded-lg bg-blue-100 dark:bg-blue-800 flex items-center justify-center flex-shrink-0">
                    <Clock className="w-5 h-5 text-blue-600 dark:text-blue-400" />
                  </div>
                  <div>
                    <p className="font-semibold text-blue-900 dark:text-blue-100 text-sm">
                      Processing Time
                    </p>
                    <p className="text-sm text-blue-700 dark:text-blue-300 mt-1">
                      Your request will be reviewed within <strong>1-3 business days</strong>. 
                      We'll process it as quickly as possible.
                    </p>
                  </div>
                </div>

                {/* Notification info */}
                <div className="flex items-start gap-3 p-4 bg-amber-50 dark:bg-amber-900/20 rounded-xl border border-amber-200 dark:border-amber-800">
                  <div className="w-10 h-10 rounded-lg bg-amber-100 dark:bg-amber-800 flex items-center justify-center flex-shrink-0">
                    <Bell className="w-5 h-5 text-amber-600 dark:text-amber-400" />
                  </div>
                  <div>
                    <p className="font-semibold text-amber-900 dark:text-amber-100 text-sm">
                      Stay Updated
                    </p>
                    <p className="text-sm text-amber-700 dark:text-amber-300 mt-1">
                      Once your request is <strong>approved</strong>, you'll see a notification 
                      when you log in. Keep checking the website for updates!
                    </p>
                  </div>
                </div>

                {/* What's next */}
                <div className="pt-2">
                  <p className="text-xs text-gray-500 dark:text-gray-400 text-center">
                    You can track your request status anytime in "My Requests"
                  </p>
                </div>
              </div>

              {/* Footer Actions */}
              <div className="px-6 py-4 bg-gray-50 dark:bg-gray-900/50 border-t border-gray-200 dark:border-gray-700 flex flex-col sm:flex-row gap-3">
                <button
                  onClick={() => setShowSuccessModal(false)}
                  className="flex-1 px-4 py-2.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-white dark:bg-gray-700 border border-gray-300 dark:border-gray-600 rounded-xl hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors"
                >
                  Submit Another Request
                </button>
                <button
                  onClick={() => {
                    setShowSuccessModal(false);
                    setActive("my-requests");
                  }}
                  className="flex-1 flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-medium text-white bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 rounded-xl transition-all shadow-lg shadow-green-600/25"
                >
                  View My Requests
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="max-w-6xl mx-auto px-3 sm:px-6 py-6 md:py-12">
        {/* Error Toast */}
        {showError && (
          <div className="mb-4">
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="flex items-start bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-xl overflow-hidden"
            >
              <div className="p-3 sm:p-4 flex items-center bg-red-100 dark:bg-red-800">
                <AlertCircle className="text-red-600 dark:text-red-400" size={20} />
              </div>
              <div className="px-3 sm:px-4 py-2 sm:py-3 flex-1">
                <p className="font-semibold text-red-800 dark:text-red-200 text-sm sm:text-base">
                  Submission Failed
                </p>
                <p className="text-xs sm:text-sm text-red-600 dark:text-red-300">
                  {errorMessage}
                </p>
              </div>
              <button
                onClick={() => setShowError(false)}
                className="p-3 sm:p-4 text-red-500 hover:text-red-700 transition-colors"
              >
                <X size={18} />
              </button>
            </motion.div>
          </div>
        )}

        {/* Card with Animation */}
        <motion.div
          initial={{ y: 30, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="bg-[var(--color-light)] rounded-lg shadow-xl border border-[var(--color-neutral-active)] relative overflow-hidden"
        >
          {/* Loading Overlay */}
          {showLoadingToast && (
            <div className="absolute inset-0 bg-white/95 backdrop-blur-sm rounded-lg z-50 flex items-center justify-center p-4">
              <div className="text-center">
                <div className="relative inline-block">
                  {/* Animated spinner rings */}
                  <div className="w-16 h-16 sm:w-20 sm:h-20 relative">
                    <div className="absolute inset-0 border-4 border-blue-200 rounded-full"></div>
                    <div className="absolute inset-0 border-4 border-transparent border-t-blue-600 rounded-full animate-spin"></div>
                    <div
                      className="absolute inset-2 border-4 border-transparent border-t-blue-400 rounded-full animate-spin"
                      style={{
                        animationDuration: "1.5s",
                        animationDirection: "reverse",
                      }}
                    ></div>
                  </div>
                </div>
                <div className="mt-4 sm:mt-6">
                  <h3 className="text-base sm:text-lg font-semibold text-gray-800 mb-2">
                    Loading Your Information
                  </h3>
                  <p className="text-xs sm:text-sm text-gray-600 max-w-sm px-2">
                    Please wait while we auto-fill your personal details from
                    your profile...
                  </p>
                  <div className="flex items-center justify-center gap-1 mt-3 sm:mt-4">
                    <div
                      className="w-2 h-2 bg-blue-600 rounded-full animate-bounce"
                      style={{ animationDelay: "0ms" }}
                    ></div>
                    <div
                      className="w-2 h-2 bg-blue-600 rounded-full animate-bounce"
                      style={{ animationDelay: "150ms" }}
                    ></div>
                    <div
                      className="w-2 h-2 bg-blue-600 rounded-full animate-bounce"
                      style={{ animationDelay: "300ms" }}
                    ></div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Step Progress Indicator */}
          <div className="px-3 sm:px-4 md:px-6 py-3 sm:py-4 border-b border-[var(--color-neutral-active)] bg-gradient-to-r from-gray-50 to-white">
            {/* Step Indicators for Request Flow */}
            {active !== "my-requests" && (
              <div className="flex items-center justify-center mb-3 sm:mb-4 overflow-x-auto">
                {tabs
                  .filter((t) => t.step > 0)
                  .map((t, index, arr) => {
                    const currentStep =
                      tabs.find((tab) => tab.id === active)?.step || 1;
                    const isCompleted = t.step < currentStep;
                    const isCurrent = t.step === currentStep;

                    return (
                      <React.Fragment key={t.id}>
                        <div className="flex flex-col items-center flex-shrink-0">
                          <div
                            className={`w-8 h-8 sm:w-10 sm:h-10 rounded-full flex items-center justify-center font-bold text-xs sm:text-sm transition-all ${
                              isCompleted
                                ? "bg-green-500 text-white"
                                : isCurrent
                                ? "bg-[var(--color-secondary)] text-white ring-2 sm:ring-4 ring-[var(--color-secondary)]/20"
                                : "bg-gray-200 text-gray-500"
                            }`}
                          >
                            {isCompleted ? "✓" : t.step}
                          </div>
                          <span
                            className={`text-[10px] sm:text-xs mt-1 font-medium text-center max-w-[60px] sm:max-w-none ${
                              isCurrent
                                ? "text-[var(--color-secondary)]"
                                : "text-gray-500"
                            }`}
                          >
                            {t.label.replace(/^\d+\.\s*/, "")}
                          </span>
                        </div>
                        {index < arr.length - 1 && (
                          <div
                            className={`w-8 sm:w-16 md:w-24 h-1 mx-1 sm:mx-2 rounded flex-shrink-0 ${
                              t.step < currentStep
                                ? "bg-green-500"
                                : "bg-gray-200"
                            }`}
                          />
                        )}
                      </React.Fragment>
                    );
                  })}
              </div>
            )}

            {/* Tab Buttons */}
            <nav
              className="flex gap-1.5 sm:gap-2 justify-center flex-wrap"
              role="tablist"
              aria-label="Form tabs"
            >
              {tabs.map((t) => {
                const isActive = active === t.id;
                const isMyRequests = t.id === "my-requests";

                return (
                  <motion.button
                    key={t.id}
                    onClick={() => setActive(t.id)}
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    transition={{ duration: 0.2 }}
                    className={`px-2.5 sm:px-4 py-1.5 sm:py-2 rounded-lg font-medium text-xs sm:text-sm transition-all ${
                      isActive
                        ? isMyRequests
                          ? "bg-blue-600 text-white shadow-md"
                          : "bg-[var(--color-secondary)] text-white shadow-md"
                        : isMyRequests
                        ? "bg-blue-50 text-blue-600 hover:bg-blue-100 border border-blue-200"
                        : "bg-gray-100 text-gray-600 hover:bg-gray-200"
                    }`}
                    role="tab"
                    aria-selected={isActive}
                  >
                    <span className="hidden sm:inline">{t.label}</span>
                    <span className="sm:hidden">{isMyRequests ? "Requests" : t.label.replace(/^\d+\.\s*/, "").split(" ")[0]}</span>
                  </motion.button>
                );
              })}
            </nav>
          </div>

          {/* Form Body */}
          <form onSubmit={handleSubmit}>
            <div className="p-3 sm:p-4 md:p-6">
              <AnimatePresence mode="wait">
                {/* Step 1: Select Document */}
                {active === "request" && (
                  <motion.div
                    key="request"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    transition={{ duration: 0.3 }}
                  >
                    <DocumentRequestTab
                      formData={formData}
                      setField={setField}
                      errors={errors}
                      isBusinessDocument={isBusinessDocument()}
                    />
                  </motion.div>
                )}

                {/* Step 2: Review Personal Info */}
                {active === "personal" && (
                  <motion.div
                    key="personal"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    transition={{ duration: 0.3 }}
                  >
                    <PersonalInfoTab
                      formData={formData}
                      setField={setField}
                      errors={errors}
                      setErrors={setErrors}
                    />
                    {/* Include Emergency Contact info in this step */}
                    <div className="mt-4 sm:mt-6 pt-4 sm:pt-6 border-t">
                      <EmergencyContactTab
                        formData={formData}
                        setField={setField}
                        errors={errors}
                      />
                    </div>
                  </motion.div>
                )}

                {/* Step 3: Upload Documents */}
                {active === "files" && (
                  <motion.div
                    key="files"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    transition={{ duration: 0.3 }}
                  >
                    <FileUploadTab
                      formData={formData}
                      setField={setField}
                      errors={errors}
                      documentType={formData.documentType}
                      storedDocuments={{
                        photo1x1: user?.photo1x1,
                        validID: user?.validID,
                      }}
                    />
                  </motion.div>
                )}

                {/* My Requests Tab */}
                {active === "my-requests" && (
                  <motion.div
                    key="my-requests"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    transition={{ duration: 0.3 }}
                  >
                    <MyRequestsTab />
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Navigation Buttons */}
            <div className="px-3 sm:px-4 md:px-6 py-3 sm:py-4 border-t border-[var(--color-neutral-active)] flex flex-col sm:flex-row justify-between items-center gap-3 sm:gap-0 bg-gray-50">
              <div className="w-full sm:w-auto">
                {active !== "request" && active !== "my-requests" && (
                  <button
                    type="button"
                    onClick={() => {
                      if (active === "personal") setActive("request");
                      else if (active === "files") setActive("personal");
                    }}
                    className="w-full sm:w-auto px-4 sm:px-5 py-2 sm:py-2.5 rounded-lg font-medium border-2 border-gray-300 text-gray-700 hover:bg-gray-100 transition-colors flex items-center justify-center gap-2 text-sm sm:text-base"
                  >
                    <span>←</span> Back
                  </button>
                )}
              </div>

              <div className="flex items-center gap-3 w-full sm:w-auto">
                {active === "request" && (
                  <button
                    type="button"
                    onClick={() => {
                      if (!formData.documentType) {
                        setErrors({
                          documentType: "Please select a document type first",
                        });
                        return;
                      }
                      if (!formData.purposeOfRequest) {
                        setErrors({
                          purposeOfRequest:
                            "Please enter the purpose of your request",
                        });
                        return;
                      }
                      setActive("personal");
                    }}
                    className="w-full sm:w-auto px-4 sm:px-5 py-2 sm:py-2.5 rounded-lg font-semibold bg-[var(--color-secondary)] text-white hover:opacity-90 transition-opacity flex items-center justify-center gap-2 text-sm sm:text-base"
                  >
                    Next Step <span>→</span>
                  </button>
                )}

                {active === "personal" && (
                  <button
                    type="button"
                    onClick={() => setActive("files")}
                    className="w-full sm:w-auto px-4 sm:px-5 py-2 sm:py-2.5 rounded-lg font-semibold bg-[var(--color-secondary)] text-white hover:opacity-90 transition-opacity flex items-center justify-center gap-2 text-sm sm:text-base"
                  >
                    Next Step <span>→</span>
                  </button>
                )}

                {active === "files" && (
                  <button
                    type="submit"
                    disabled={loading}
                    className="w-full sm:w-auto px-5 sm:px-6 py-2 sm:py-2.5 rounded-lg font-semibold bg-green-600 text-white hover:bg-green-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 text-sm sm:text-base"
                  >
                    {loading ? (
                      <>
                        <Loader2 className="w-4 h-4 animate-spin" />
                        Submitting...
                      </>
                    ) : (
                      <>✓ Submit Request</>
                    )}
                  </button>
                )}
              </div>
            </div>
          </form>
        </motion.div>

        {/* small help block */}
        <div className="px-2 sm:p-0 text-center sm:text-left mt-3 sm:mt-4 text-xs sm:text-sm text-[var(--color-text-secondary)]">
          By submitting, you agree to our terms and privacy policy. Processing
          usually takes 3–5 business days.
        </div>
      </div>
    </div>
  );
}
